---
title: "Pollock_Effort_Sample_Fraction"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(here)
library(gmodels)

all_effort <- readRDS("data/AK_Effort_Trawl/Gasper_data/Chinooky_Rates_merged.RDS") %>%
  #ELLR == NO OBSERVER, OBS == OBSERVER
filter(fmp_sub_area_code == "GOA", target =="pollock") %>%
  mutate(length_category = case_when(ves_akr_length < 125 & year < 2013 ~ "Small",
                                     ves_akr_length > 124 & year < 2013 ~ "Large",
                                     ves_akr_length > 59 & year > 2012 ~ "Large",
                                     ves_akr_length < 60 & year > 2012 ~ "Small",
                                     TRUE ~ as.character(ves_akr_length)),
         region = case_when(reporting_area_code == "610" ~ "E.APEN", 
                            reporting_area_code == "620" ~ "W.APEN",  
                            reporting_area_code %in% c("630") ~ "NW.GOA", 
                            reporting_area_code %in% c("640", "640 ") ~ "NE.GOA", 
                            reporting_area_code %in% c("649") ~ "NE.NW.GOA", #there are about 600 records from this stat area- need to divide them in half between NE and NW GOA, can do this based on ADFG numbers. check w ole before doing this.  
                            TRUE ~ "TBD")) %>% #there are none of these. 
        separate(trip_target_date, into = c("year", "month", "day"), sep = "-")


# data <- all_effort %>%
#   filter(fmp_sub_area_code == "GOA")
# 
# table(data$year[!is.na(data$el_report_id)],data$processing_sector[!is.na(data$el_report_id)],exclude=NULL)

```


```{r parce effort data, echo =FALSE,message=FALSE,warning=FALSE}
#bring in obs and unobs compiled effort data and summarize to boat days
all_effort_boat_days<- all_effort %>%
        group_by(year,month,region,length_category,processing_sector) %>%
        dplyr::summarise(
          all_boat_days=n() ,
          all_vessel_count = n_distinct(catcher_vessel_id),
          #retained_catch_MT=sum(retained_gf_weight), #retained catch only starts in 2009 for some reason
          all_catch_MT=sum(total_gf_basis_weight))

#summarized observed effort data
#first just summarize observed effort off of the total effort 
#DONT USE THIS UNTIL JW CAN FIGURE OUT THE CATCH REPORT CODES
# obs_effort_boat_days <- all_effort %>%
#   filter(catch_report_type_code=="OBS") %>%
#   group_by(year,month,region,length_category,processing_sector) %>%
#   dplyr::summarise(
#     obs_boat_days=n(),
#     obs_vessel_count=n_distinct(catcher_vessel_id),
#     #retained_catch_MT=sum(retained_gf_weight), #retained catch only starts in 2009 for some reason
#     obs_catch_MT=sum(total_gf_basis_weight))

# unobs_effort_boat_days <- all_effort %>%
#   filter(!catch_report_type_code=="OBS") %>%
#   group_by(year,month,region,length_category,processing_sector) %>%
#   dplyr::summarise(
#     unobs_boat_days=n(),
#     unobs_vessel_count=n_distinct(catcher_vessel_id),
#     #retained_catch_MT=sum(retained_gf_weight), #retained catch only starts in 2009 for some reason
#     unobs_catch_MT=sum(total_gf_basis_weight))

# effort <- left_join(all_effort_boat_days, obs_effort_boat_days) %>%
#   left_join(unobs_effort_boat_days) %>%
#  mutate(obs_boat_days= replace_na(obs_boat_days,0),
#         obs_vessel_count= replace_na(obs_vessel_count,0),
#         obs_catch_MT= replace_na(obs_catch_MT,0))
```

```{r bring in other observed effort csv}
obs_effort <- read.csv("data/AK_Effort_Trawl/Alaska trawl observed effort.csv") 
```

```{r put all effort into season format}
#see what JOrdan brings back... if it is not helpful then figure out this code to transform the total data into seasons

#In general I use the spring = 4-5, summer=6-7,fall=8-10.  Winter=others, though

all_effort_boat_days<- all_effort_boat_days %>%
 select(-c(all_vessel_count, all_catch_MT)) %>%
   spread(month, all_boat_days) %>%
    replace(., is.na(.), 0) %>%
    as.data.frame()

MONTH.STRUCTURE="FOUR"
#arrange month structure
if(MONTH.STRUCTURE=="FOUR"){
 all_effort_boat_days$month.winter.2 <- rowSums(all_effort_boat_days[,WINTER.MONTH[1:3]])
 all_effort_boat_days$month.winter.1 <- rowSums(all_effort_boat_days[,WINTER.MONTH[4:5]])
 all_effort_boat_days$month.spring <- rowSums(all_effort_boat_days[,SPRING.MONTH])
 all_effort_boat_days$month.summer <- rowSums(all_effort_boat_days[,SUMMER.MONTH])
 all_effort_boat_days$month.fall   <- rowSums(all_effort_boat_days[,FALL.MONTH])
}

if(MONTH.STRUCTURE=="FRAM"){
  all_effort_boat_days$month.winter.2 <- all_effort_boat_days[,WINTER.MONTH[1]]
  all_effort_boat_days$month.winter.1 <- rowSums(all_effort_boat_days[,WINTER.MONTH[2:4]]) 
  all_effort_boat_days$month.spring <- rowSums(all_effort_boat_days[,SPRING.MONTH])
  all_effort_boat_days$month.summer <- rowSums(all_effort_boat_days[,SUMMER.MONTH])
  all_effort_boat_days$month.fall   <- rowSums(all_effort_boat_days[,FALL.MONTH])
}

all_effort_boat_days$year.wint.2  <- all_effort_boat_days$year-1

```

```{r echo=FALSE}
#small boats/year 
effort %>%
  select(1:5,9,12) %>%
  filter(length_category == "Small", processing_sector == "S") %>%
  gather(6:7, key = "category", value = "boat_days") %>%
  # group_by(year,region, processing_sector,category)%>%
  # summarise(boat_days=sum(boat_days),
  #           boat_days= replace_na(boat_days,0)) %>%
  ggplot() +
  geom_bar(aes(x=year,y=boat_days, fill = category), position="dodge", stat="identity",alpha = 0.8) +
  facet_grid(region~month,scales="free") +
  ggtitle("Annual Boat Days (Small Pollock)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme_classic()

#large
effort %>%
  select(1:5,9,12) %>%
  filter(length_category == "Small", processing_sector == "S") %>%
  gather(6:7, key = "category", value = "boat_days") %>%
  # group_by(year,region, processing_sector,category)%>%
  # summarise(boat_days=sum(boat_days),
  #           boat_days= replace_na(boat_days,0)) %>%
  ggplot() +
  geom_bar(aes(x=year,y=boat_days, fill = category), position="dodge", stat="identity",alpha = 0.8) +
  facet_grid(region~month,scales="free") +
  ggtitle("Annual Boat Days (Small Pollock)") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme_classic()


```

