---
title: "Pollock_Observer_Sample_Fraction"
output: html_document
---
Goal of this doc is to summarize the fraction of haul an observer surveys, given there is an observer on board.   
Also used J. Gasper's data, which rate information based on species counts. This information is also estimated from unobserved hauls by the regional office, but I don't think we need that. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message=FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(gmodels)
library(gplots)

all_effort <- readRDS("data/AK_Effort_Trawl/Gasper_data/Chinooky_Rates_merged.RDS") %>%
filter(fmp_sub_area_code == "GOA", target =="pollock") %>%
  mutate(length_category = case_when(ves_akr_length < 125 & year < 2013 ~ "Small",
                                     ves_akr_length > 124 & year < 2013 ~ "Large",
                                     ves_akr_length > 59 & year > 2012 ~ "Large",
                                     ves_akr_length < 60 & year > 2012 ~ "Small",
                                     TRUE ~ as.character(ves_akr_length)),
         region = case_when(reporting_area_code == "610" ~ "E.APEN", 
                            reporting_area_code == "620" ~ "W.APEN",  
                            reporting_area_code %in% c("630") ~ "NW.GOA", 
                            reporting_area_code %in% c("640", "640 ") ~ "NE.GOA", 
                            reporting_area_code %in% c("649") ~ "NE.NW.GOA", #there are about 600 records from this stat area- need to divide them in half between NE and NW GOA, can do this based on ADFG numbers. check w ole before doing this.  
                            TRUE ~ "TBD")) %>% #there are none of these. 
        separate(trip_target_date, into = c("year", "month", "day"), sep = "-")

# data <- all_effort %>%
#   filter(fmp_sub_area_code == "GOA")
# 
# table(data$year[!is.na(data$el_report_id)],data$processing_sector[!is.na(data$el_report_id)],exclude=NULL)


col.br= colorRampPalette(c("white", "blue","purple","red")) #colors for heatmap
every_nth = function(n) {
  return(function(x) {x[c(TRUE, rep(FALSE, n - 1))]})
}
```


 
```{r cars}
 


```
 